package com.shadiwaley.server.crm.domain;

public enum CrmTimelineEventType {
    CASE_CREATED,
    CASE_UPDATED,
    CRM_ASSIGNED,
    STAGE_CHANGED,
    PRIORITY_CHANGED,
    NOTE_ADDED,
    FOLLOW_UP_SCHEDULED,
    FOLLOW_UP_COMPLETED,
    FOLLOW_UP_RESCHEDULED,
    CASE_CLOSED,
    CASE_REOPENED,

    PROPOSAL_SENT,
    PROPOSAL_VIEWED,
    PROPOSAL_INTERESTED,
    PROPOSAL_SHORTLISTED,
    PROPOSAL_MEETING_DISCUSSION,
    PROPOSAL_ACCEPTED,
    PROPOSAL_REJECTED,
    PROPOSAL_NOT_INTERESTED,
    PROPOSAL_CANCELLED,
    PROPOSAL_EXPIRED,

    PIPELINE_STAGE_CHANGED,
    PIPELINE_ACCEPTED,
    PIPELINE_REJECTED,
    PIPELINE_CLOSED,
    PIPELINE_NOTE_ADDED,
    PIPELINE_FOLLOW_UP_SCHEDULED,


    AUTOPILOT_QUEUE_GENERATED,
    AUTOPILOT_QUEUE_READY,
    AUTOPILOT_DISPATCH_PREVIEWED,
    AUTOPILOT_DISPATCH_SENT,
    AUTOPILOT_DISPATCH_SKIPPED,
    AUTOPILOT_DISPATCH_POSTPONED,
    AUTOPILOT_RESPONSE_RECORDED,
    AUTOPILOT_PROPOSAL_CREATED,


}