
package com.shadiwaley.server.audit.domain;

public enum AuditAction {
    PROFILE_APPROVED,
    PROFILE_REJECTED,
    MEDIA_APPROVED,
    MEDIA_REJECTED,

    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_STATUS_CHANGED,
    EMPLOYEE_PASSWORD_RESET,
    EMPLOYEE_DEACTIVATED,

    CRM_CASE_CREATED,
    CRM_CASE_ASSIGNED,
    CRM_CASE_STATUS_CHANGED,
    CRM_NOTE_ADDED,
    CRM_FOLLOW_UP_CREATED,

    RISHTA_REQUEST_SENT,
    RISHTA_REQUEST_ACCEPTED,
    RISHTA_REQUEST_REJECTED,

    CHAT_MESSAGE_REPORTED,
    CHAT_ROOM_BLOCKED,
    CHAT_ROOM_CLOSED,

    SYSTEM_ACTION,
    MATCH_SUGGESTIONS_VIEWED,
    MATCH_FILTER_APPLIED,
    CANDIDATE_PREVIEW_OPENED,
    COMPATIBILITY_VIEWED,
    PROPOSAL_SENT_FROM_FIND_MATCHES,
    PROPOSAL_SENT_FROM_ASSISTED_DISPATCH,

    PLAN_ASSIGNED,
    PLAN_CHANGED,
    MANUAL_PAYMENT_RECORDED,
    PAYMENT_MARKED_PAID,
    PAYMENT_MARKED_PENDING,
    PAYMENT_REFUNDED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_EXPIRED,

    PIPELINE_STAGE_CHANGED,
    PIPELINE_ACCEPTED,
    PIPELINE_REJECTED,
    PIPELINE_CLOSED,
    PIPELINE_NOTE_ADDED,
    PIPELINE_FOLLOW_UP_SCHEDULED,

    AUTOPILOT_QUEUE_GENERATED,
    AUTOPILOT_QUEUE_READY,
    AUTOPILOT_DISPATCH_PREVIEWED,
    AUTOPILOT_DISPATCH_SENT,
    AUTOPILOT_DISPATCH_SKIPPED,
    AUTOPILOT_DISPATCH_POSTPONED,
    AUTOPILOT_RESPONSE_RECORDED,
    AUTOPILOT_PROPOSAL_CREATED,

    CHAT_INTERNAL_NOTE_ADDED,
    CHAT_ROOM_STATUS_UPDATED,
    CHAT_MESSAGE_MODERATED,
    CHAT_ROOM_REPORTED,
    CHAT_ROOM_UNBLOCKED,

    CHAT_ASSIGNMENT_UPDATED,
    CHAT_DECISION_RECORDED,
    CHAT_FOLLOW_UP_SCHEDULED,
}