package com.shadiwaley.server.onboarding.application.service;

import com.shadiwaley.server.media.domain.MediaType;
import com.shadiwaley.server.media.domain.WhatsappConsent;
import com.shadiwaley.server.onboarding.dto.response.OnboardingOptionsResponse;
import com.shadiwaley.server.parent.domain.ParentRelation;
import org.springframework.stereotype.Service;

import java.util.Arrays;
import java.util.List;

@Service
public class OnboardingOptionsService {

    public OnboardingOptionsResponse getOptions() {
        return OnboardingOptionsResponse.builder()
                .parentRelation(toNames(ParentRelation.values()))
                .education(List.of(
                        "TENTH",
                        "TWELFTH",
                        "GRADUATE",
                        "POST_GRADUATE",
                        "DOCTORATE",
                        "OTHER"
                ))
                .quranLevel(List.of(
                        "BASIC",
                        "INTERMEDIATE",
                        "HAFIZ",
                        "AALIM",
                        "OTHER"
                ))
                .namaazRegularity(List.of(
                        "ALWAYS",
                        "OFTEN",
                        "SOMETIMES",
                        "RARELY"
                ))
                .professionType(List.of(
                        "JOB",
                        "BUSINESS",
                        "STUDENT",
                        "HOMEMAKER",
                        "SELF_EMPLOYED",
                        "OTHER"
                ))
                .houseType(List.of(
                        "OWN_HOUSE",
                        "RENTED",
                        "FAMILY_HOUSE",
                        "OTHER"
                ))
                .familyType(List.of(
                        "JOINT",
                        "NUCLEAR"
                ))
                .preferredEducation(List.of(
                        "TENTH",
                        "TWELFTH",
                        "GRADUATE",
                        "POST_GRADUATE",
                        "DOCTORATE",
                        "ANY"
                ))
                .preferredFamilyType(List.of(
                        "JOINT",
                        "NUCLEAR",
                        "ANY"
                ))
                .caste(List.of(
                        "ANSARI",
                        "KHAN",
                        "PATHAN",
                        "SHEIKH",
                        "SAI",
                        "SAIYED",
                        "QURESHI",
                        "MANSURI",
                        "RANGREZ",
                        "IDRISI",
                        "MALIK",
                        "SIDDIQUI",
                        "FAROOQUI",
                        "ABBASI",
                        "HASHMI",
                        "MIRZA",
                        "MUGHAL",

                        // Bihar + UP common muslim biradari
                        "RAEEN",
                        "DHUNIYA",
                        "NALBAND",
                        "KUNJRA",
                        "SALMANI",
                        "JULAHA",
                        "HALALKHOR",
                        "FAKIR",
                        "MOMIN",
                        "USMANI",
                        "BAGBAN",
                        "MADARI",
                        "HUSSAINI",
                        "CHHIPPI",
                        "MEHTAR",
                        "BHATIYARA",
                        "TELI",
                        "ATAR",
                        "NADAF",
                        "MIRSHIKAR",
                        "KADRI",
                        "NOORI",
                        "CHAUDHARY",
                        "BISATI",
                        "DHOBI",
                        "SAIFI",
                        "MULTANI",
                        "BANDHWA",
                        "QASAB",
                        "QASMI",
                        "WARSI",
                        "ASHRAFI",
                        "BAIG",
                        "BEG",
                        "ALVI",
                        "TURK",
                        "AFGHANI",
                        "ARAIN",
                        "BENGALI",
                        "OTHERS"
                ))
                .preferredCaste(List.of(
                        "ANY",
                        "ANSARI",
                        "KHAN",
                        "PATHAN",
                        "SHEIKH",
                        "SAI",
                        "SAIYED",
                        "QURESHI",
                        "MANSURI",
                        "RANGREZ",
                        "IDRISI",
                        "MALIK",
                        "SIDDIQUI",
                        "FAROOQUI",
                        "ABBASI",
                        "HASHMI",
                        "MIRZA",
                        "MUGHAL",
                        "RAEEN",
                        "DHUNIYA",
                        "NALBAND",
                        "KUNJRA",
                        "SALMANI",
                        "JULAHA",
                        "FAKIR",
                        "MOMIN",
                        "USMANI",
                        "QASMI",
                        "WARSI",
                        "ASHRAFI",
                        "BAIG",
                        "BEG",
                        "ALVI",
                        "ARAIN",
                        "OTHERS"
                ))
                .maslak(List.of(
                        "SUNNI",
                        "DEOBANDI",
                        "BARELVI",
                        "AHL_E_HADITH",
                        "SALAFI",
                        "HANAFI",
                        "SHAFI",
                        "SHIA",
                        "SUFI",
                        "JAMAT_E_ISLAMI",
                        "TABLIGHI",
                        "OTHER"
                ))
                .preferredMaslak(List.of(
                        "ANY",
                        "SUNNI",
                        "DEOBANDI",
                        "BARELVI",
                        "AHL_E_HADITH",
                        "SALAFI",
                        "HANAFI",
                        "SHAFI",
                        "SHIA",
                        "SUFI",
                        "JAMAT_E_ISLAMI",
                        "TABLIGHI",
                        "OTHER"
                )).state(List.of(
                        "BIHAR"
                )).preferredState(List.of(
                        "Any",
                        "BIHAR"
                )).district(List.of(
                        "SIWAN",
                        "CHHAPRA",
                        "GOPALGANJ",
                        "PATNA",
                        "HAJIPUR"
                )).preferredDistrict(List.of(
                        "ANY",
                        "SIWAN",
                        "CHHAPRA",
                        "GOPALGANJ",
                        "PATNA",
                        "HAJIPUR"
                ))
                .mediaType(toNames(MediaType.values()))
                .whatsappConsent(toNames(WhatsappConsent.values()))
                .build();
    }

    private List<String> toNames(Enum<?>[] values) {
        return Arrays.stream(values)
                .map(Enum::name)
                .toList();
    }
}