package com.shadiwaley.server.notification.domain;

public enum NotificationType {
    PROFILE_INCOMPLETE,
    PROFILE_READY_FOR_REVIEW,
    PROFILE_APPROVED,
    PROFILE_REJECTED,

    MEDIA_APPROVED,
    MEDIA_REJECTED,

    RISHTA_RECEIVED,
    RISHTA_ACCEPTED,
    RISHTA_REJECTED,

    CHAT_OPENED,

    SUBSCRIPTION_EXPIRING,
    AUTOPILOT_DISPATCH,

    PROFILE_MILESTONE_EARNED,
    INVESTMENT_DECAY,

    SYSTEM_MESSAGE,

    RISHTA_CANCELLED,
}